server:
  port: 8085

spring:
  datasource:
    url: jdbc:sqlserver://127.0.0.1:1433;databaseName=whatsapp_users_dev;encrypt=false;trustServerCertificate=true
    username: sa
    password: Saad@12345
  jpa:
    show-sql: true
  flyway:
    enabled: true

logging:
  level:
    com.whatsapp.userservice: DEBUG
    org.springframework.security: DEBUG
